Fraktur UB Tübingen
cneud/ocr-gt pull request #47
Opened 2022-01-18 15:18 UTC by lena-hinrichsen

add https://github.com/ubtue/gt-fraktur

CC @ubtue

2022-01-25 17:17 UTC, cneud requested changes
Multiple values need to be added as bullet points. THX for the addition!

2022-01-25 17:17 UTC, cneud commented on _data/ocr-gt.yml
> +        format: PAGE-XML, ALTO, TEI, TXT, PDF, DOCX
```suggestion
        format: 
            - PAGE-XML
            - ALTO
            - TEI
            - Text
            - PDF 
            - DOCX
```

2022-01-26 09:50 UTC, obrandt approved these changes

2022-01-26 09:51 UTC, obrandt approved these changes

2022-01-26 09:53 UTC, merged